version: '3.8'

services:
  admin:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: ["/bin/bash", "./entrypoint.sh"]
    restart: unless-stopped
