"""
Django settings for klaw_app project.

Generated by 'django-admin startproject' using Django 4.1.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/
import os
# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = "django-insecure-mqktx_(*-54eiz5@$d3&ke=ifm2rx_df&4(2u&tz(pxn6pn$uo"
SECRET_KEY = os.getenv('SECRET_KEY', '^bjzq+3+i%r=t%q9rr^w0r@7lm=i2o-6p7by8&)u&04g$')
DEBUG = True  # Set this to False for production
#DATABASE_URL = "mongodb+srv://igniteprojects02:igniteadmin@flaws.9pgqc.mongodb.net/klaw_db"
ALLOWED_HOSTS = ["*"]

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = False

#ALLOWED_HOSTS = ['Klaw.onrender.com']


# Application definition


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #'rest_framework_simplejwt.token_blacklist',
    'rest_framework',
    'admin_panel',  
    'corsheaders',
    
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    
    
]


CORS_ALLOW_ALL_ORIGINS = True
#CORS_ALLOW_ALL_ORIGINS = True

#CORS_ALLOWED_ORIGINS = []

CORS_ALLOWED_METHODS = [
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
    'OPTIONS',
    
    ]

ROOT_URLCONF = "klaw_app.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "klaw_app.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'djongo',
#         'NAME': 'klaw_db',  # Your database name
#     }
# }



DATABASES = {
    'default': {
        'ENGINE': 'djongo',  # Use Djongo as the engine
        'NAME': 'klaw_db1',  # Your database name in MongoDB Atlas
        'CLIENT': {
            'host': 'mongodb+srv://igniteprojects02:igniteadmin@flaws.9pgqc.mongodb.net/flawsapp?retryWrites=true&w=majority&ssl=true&appName=klaw_app',  # Your MongoDB Atlas connection string
            'retryWrites': True,
            'w': 'majority',
        },
    }
}


# DATABASES = {
#     'default': {
#         'ENGINE': 'djongo',
#         'NAME': os.getenv('DATABASE_NAME', 'klaw_db'),  # Default to 'klaw_db' if not set
#         'CLIENT': {
#             'host': os.getenv('DATABASE_URL', 'mongodb+srv://igniteprojects02:igniteadmin@flaws.9pgqc.mongodb.net/klaw_db'),  # Remove the extra space at the end
#             'retryWrites': True,
#             'w': 'majority',
#         },
#     }
# }

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        # 'adminpanel_authentication.CustomJWTAuthentication'
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}



from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': True,
    'SIGNING_KEY': 'your-secret-key',
    'ALGORITHM': 'HS256',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'JTI_CLAIM': 'jti',  # This will store the unique JWT ID (jti)
}

#    'BLACKLIST_AFTER_ROTATION': True,


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators
#AUTH_USER_MODEL = 'mobile_api.UserSignup'

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/
import os
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
