from django.urls import path
from .views import (
    AdminLoginView, CourseBasicInfoView, CourseOutcomesView, CourseSyllabusView,
    CourseQuestionsView, CourseMaterialsView, CourseDeleteView, ToggleCourseStatusView,
    GetCoursesView, ContactFormView, CreateBlogView, ListBlogsView,
    SingleBlogView, EditBlogView, ToggleBlogStatusView, DeleteBlogView, CourseDetailView,
    PushNotificationView, NotificationHistoryView,ProcessCourseAPIView,list_users,view_user_details,ToggleUserStatus,
)

urlpatterns = [
    path('login/', AdminLoginView.as_view(), name='admin-login'),
    path('course-basic-info/', CourseBasicInfoView.as_view(), name='course-basic-info'),
    path('course-basic-info/<str:course_code>/', CourseBasicInfoView.as_view(), name='course-basic-info-edit'),
    path('course-outcomes/', CourseOutcomesView.as_view(), name='course-outcomes'),
    path('course-syllabus/', CourseSyllabusView.as_view(), name='course-syllabus'),
    path('course-questions/', CourseQuestionsView.as_view(), name='course-questions'),
    path('course-materials/', CourseMaterialsView.as_view(), name='course-materials'),
    path('course-outcomes/<str:course_code>/', CourseOutcomesView.as_view(), name='course-outcomes'),
    path('course-syllabus/<str:course_code>/', CourseSyllabusView.as_view(), name='course-syllabus'),
    path('course-questions/<str:course_code>/', CourseQuestionsView.as_view(), name='course-questions'),
    path('course-materials/<str:course_code>/', CourseMaterialsView.as_view(), name='course-materials'),
    path('course-delete/', CourseDeleteView.as_view(), name='course-delete'),
    path('process/', ProcessCourseAPIView.as_view(), name='process-course'),
    path('toggle-course/<str:course_code>/', ToggleCourseStatusView.as_view(), name='toggle-course-status'),
    path('get-courses/', GetCoursesView.as_view(), name='get-courses'),
    path('courses/<str:course_code>/', CourseDetailView.as_view(), name='course-detail'),
    path('contact/', ContactFormView.as_view(), name='contact-form'),
    path('create-blog/', CreateBlogView.as_view(), name='create-blog'),
    path('blogs/', ListBlogsView.as_view(), name='list-blogs'),
    path('blogs/<int:id>/', SingleBlogView.as_view(), name='single-blog'),
    path('edit-blog/<int:id>/', EditBlogView.as_view(), name='edit-blog'),
    path('toggle-blog/<int:id>/', ToggleBlogStatusView.as_view(), name='toggle-blog-status'),
    path('delete-blog/<int:id>/', DeleteBlogView.as_view(), name='delete-blog'),
    path('push-notification/', PushNotificationView.as_view(), name='push-notification'),
    path('notification-history/', NotificationHistoryView.as_view(), name='notification-history'),
    path('users/', list_users, name='list_users'),
    path('toggle_status/<int:user_id>/', ToggleUserStatus.as_view(), name='toggle_user_status'),
    path('view_user/<int:user_id>/', view_user_details, name='view_user_details'),
]